### ISSUE TITLE
Introduce travis

### ISSUE THREAD

**Issue by ngtk** [Altech/red_blocks#1]

**Comment by ngtk** [comment]
@Altech Can you add this repository to https://travis-ci.org? I can't do it because I'm not repository owner. Of course, I'll do the task to set up travis after that if it bother you.

**Comment by Altech** [comment]
I have activated travis-ci.

**Comment by ngtk** [comment]
Thank you!

**Comment by ngtk** [comment]
https://travis-ci.org/Altech/red_blocks
